name: Deploy Connection Generator to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'web/**' # Ne se déclenche que si le dossier web est modifié
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web' # Dossier contenant ton index.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4